### ISSUE TITLE
Crash in Pirikium 0.11.0

### ISSUE THREAD

**Issue by npinochet** [Quozul/Pirikium#4]
Pirikium crashed with the following error message:

```
namegen/namegen.lua:190: bad argument #1 to 'lines' (namegen/namegen.index: No such file or directory)
stack traceback:
	errorhandler.lua:20: in function 'handler'
	[string "boot.lua"]:637: in function <[string "boot.lua"]:633>
	[C]: in function 'lines'
	namegen/namegen.lua:190: in function 'parse_index'
	namegen/namegen.lua:510: in main chunk
	[C]: in function 'require'
	main.lua:25: in main chunk
	[C]: in function 'require'
	[string "boot.lua"]:475: in function <[string "boot.lua"]:311>
	[C]: in function 'xpcall'
	[string "boot.lua"]:645: in function <[string "boot.lua"]:639>
	[C]: in function 'xpcall'
	[string "boot.lua"]:657: in function <[string "boot.lua"]:630>
```

[If you can, describe what you've been doing when the error occurred]
I just opened the game :(

---
Version: 0.11.0
System: OS X

**Comment by Quozul** [comment]
Sorry for the late answer. This crash occur because the game require an extra folder which is `namegen`, you can find [this folder here on GitHub](https://github.com/Quozul/Pirikium/tree/v0.11.0/namegen), you'll just have to place it in the same directory as the `.love` file.

```
.
├─ Pirikium-v0.11.0.love
└─ namegen
  ├─ namegen.index
  └─ data
    └─ *.cfg
```
If you don't wan't to download this folder you can try launching the game from a terminal.

Anyways, I've [pushed a new commit](https://github.com/Quozul/Pirikium/commit/6dbceaaf74f6aa5bf3cd2fce138fd4e3a62efda0) that removes namegen so the crash shouldn't occur anymore, I also created a [new release](https://github.com/Quozul/Pirikium/releases/tag/v0.12.0-dev.2) where you can find a `.love` file included.
